// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZnEUO5dTj_5Y9sQd_ETYViBll9Gi7oWY',
    appId: '1:97771323958:web:0b9cfbea4188db7adcce97',
    messagingSenderId: '97771323958',
    projectId: 'task-management-eb3bf',
    authDomain: 'task-management-eb3bf.firebaseapp.com',
    storageBucket: 'task-management-eb3bf.appspot.com',
    measurementId: 'G-EVRGPPREMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2gmWTKOk9JC3RfhaQw0G1RmU-v87MxZY',
    appId: '1:97771323958:android:a643cf7b851f3127dcce97',
    messagingSenderId: '97771323958',
    projectId: 'task-management-eb3bf',
    storageBucket: 'task-management-eb3bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpsc_I5ulN5MUPkfjNtlGr52jDocK9abA',
    appId: '1:97771323958:ios:09c9aefc6f77b762dcce97',
    messagingSenderId: '97771323958',
    projectId: 'task-management-eb3bf',
    storageBucket: 'task-management-eb3bf.appspot.com',
    iosBundleId: 'com.noorisys.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZnEUO5dTj_5Y9sQd_ETYViBll9Gi7oWY',
    appId: '1:97771323958:web:4440b964fb893617dcce97',
    messagingSenderId: '97771323958',
    projectId: 'task-management-eb3bf',
    authDomain: 'task-management-eb3bf.firebaseapp.com',
    storageBucket: 'task-management-eb3bf.appspot.com',
    measurementId: 'G-L0YW49TFJR',
  );

}